### PR TITLE
Transifex 4.3beta8 strings

### PR DESCRIPTION
**Pull request by Eselce**
Pending until version bump 4.3beta8: More translations to come!

### CODE REVIEW

**Comment by arantius** [comment]
No PRs for strings please.  Commit them to Transifex only.

**Comment by Eselce** [comment]
> No PRs for strings please. Commit them to Transifex only.

Not for the first time: Your procedure isn't working (which is annoying for foreign language users).
The one that is crashing the AddOn is, that placeholders are not handled within transifex.

This PR is just the collection of the data in transifex for all languages (except for english, which is untouched).

I just do volunteer to get this right, because of the impact on my fellow users. If you want to do that, okay.
For you, it's just the difference of downloading and committing vs. merging. Your late commit is fast, error prone, and not verified. It's also not tested by the native users. This doesn't sound sensible to me.

**Comment by arantius** [comment]
> This PR is just the collection of the data in transifex for all languages (except for english, which is untouched).

Except, how do I know that?

**Comment by Eselce** [comment]
> > This PR is just the collection of the data in transifex for all languages (except for english, which is untouched).
> 
> Except, how do I know that?

The title "`Transifex` ..." shall imply that. I can only say: Trust me. :grin:

Or you can check it. I could also change the comment or the title or the name of the branch.

**Pull request closed without merging**
