### PR TITLE
Support downgrading evalContentVersion on scripts

### PR DESCRIPTION
**Pull request by ToadKing**
Ran into this developing my last patch. Allowing for version downgrades on evalContent should be allowed.

### CODE REVIEW

**Comment by Sxderp** [comment]
Agreed, I've run into this a few times before too. I'd just remove the script and move on. But this is better.

**Comment by arantius** [comment]
Can you clarify this for me?  What's the expected situation where this number goes down?

**Comment by Sxderp** [comment]
> Can you clarify this for me? What's the expected situation where this number goes down?

Mostly development builds. Suppose your testing something and then roll back. Sometimes you're stuck with incompatible scripts and need make a new one, copy paste, and continue on.

**Comment by ToadKing** [comment]
It can also be useful to users downgrading from a beta release to a stable release, in case the evalContent in the beta breaks something.

**Pull request merged**
