### PR TITLE
Add zh_TW translations.

### PR DESCRIPTION
**Pull request by s8321414**
I added zh_TW translations, please review and merge it :smiley:

### CODE REVIEW

**Comment by Eselce** [comment]
@s8321414 All locale input (translations) have to be stored at [Transifex.com](https://www.transifex.com/greasemonkey/). On the [dashboard page](https://www.transifex.com/greasemonkey/greasemonkey/dashboard/), you'll find a link `Request a language` at the bottom right (registration required). Then you can easily edit (and comment) the translations. This PR will probably be close soon by @arantius.

**Comment by Eselce** [comment]
BTW: Welcome to the translation team!

**Comment by Eselce** [comment]
> The _Chinese (Taiwan)_ language was requested for the `Greasemonkey` project.

**Comment by Eselce** [comment]
@s8321414 Moved your translations to `transifex.com`. Only recently added strings `close` and `saving` are missing (please add).

This may be closed. See also #2897.

**Comment by Eselce** [comment]
Thanks. Translation completed (for now).

**Comment by s8321414** [comment]
So this PR can be closed now, I will delete my fork :smiley:

**Comment by arantius** [comment]
Thanks for the contribution!  Confirmed data is in transifex, so it will be in the next build.

**Pull request closed without merging**
