### PR TITLE
Allow scripts to execute on the `file:` protocol

### PR DESCRIPTION
**Pull request by Sxderp**
#2693

### CODE REVIEW

**Comment by Sxderp** [comment]
In #2782 I mentioned that I didn't recall how I stumbled upon the error. Well, I figured it out. It was when I was working on this pull request. I found that out as I was going over the tests that I had `git stash` (and subsequently forgot about).

I've rebased this pull on to #2782. As well as pushed the tests.

**Comment by arantius** [comment]
I checked out this branch and installed this script:

```
// ==UserScript==
// @name     Run-on-file
// @version  1
// @grant    none
// @include  file:///*
// ==/UserScript==

console.log('GM script running on file!');
```

But I don't see the log message.  This switches to `webNavigation.onCommitted` to detect execution time, which AFAICT does not fire for files (because they're not "web" navigations?).

**Comment by Sxderp** [comment]
> But I don't see the log message. 

Interesting. At the moment I don't have access to newer versions of FF to test, but it worked on RHEL6 FF 52.5.1. And if I'm remembering correctly it should have worked on elementaryOS (Ubuntu based) FF 57.? (although it _may_ have been on nightly and therefore FF 59.?).

I don't recall testing on my Windows.

**Comment by arantius** [comment]
I'm testing on Ubuntu, FF 59.

**Comment by erosman** [comment]
> But I don't see the log message. This switches to webNavigation.onCommitted to detect execution time, which AFAICT does not fire for files (because they're not "web" navigations?).

I have an addon where I use `webRequest` which also doesn't fire on local locations i.e. `about: view-source: moz-extension: chrome: resource: file:`
I guess they used the same approach for `webNavigation`

I overcame the problem by adding `tabs.onUpdated` listener.

Note: `tabs.onUpdated` fires too many times.
You would need to check for `changeInfo.url` and then use `tabInfo.url` and then avoid reinjecting the same script again.

However ............... It says here as well the API doesn't allow injection to file at all (unless manually allowed by the user) :(

https://stackoverflow.com/questions/33575973/how-to-get-content-scripts-to-execute-in-file-urls-in-a-chrome-extension

https://stackoverflow.com/questions/34250957/google-chrome-chromium-event-filter-local-file-hostname

**Comment by Sxderp** [comment]
> I'm testing on Ubuntu, FF 59.

Weird. I just double checked on elementaryOS FF 57 + 59, both worked. Also tested on Windows 59, worked as well.

I could start up a Ubuntu VM and see if it's just that platform (which is again, weird).

---

I tested by typing the path into the URL and by running `firefox ./test.html`. I was unable to test drag + drop on the elementaryOS (RIP, can't seem to drag files using whatever the standard manager is). But drag + drop worked on Windows.

**Comment by Sxderp** [comment]
Oh, I just rebased this and #2782 on master. So if you test, then make sure you account for #2652

**Comment by erosman** [comment]
Is there a beta to test?

**Comment by Sxderp** [comment]
> Is there a beta to test?

Nothing has been pushed to AMO. You can always check out my branch and manually install from file or load temporary add-on.

**Comment by Sxderp** [comment]
I grabbed an Ubuntu VM (nothing to install an actual copy on at the moment) and see no problems. After I enabled GM (since it's currently off by default), I performed the same tests as above, drag+drop, URI navigation, and `firefox index.html`. With all three I saw the logged message in the page console.

**Comment by arantius** [comment]
Tried to test again and I agree that it works.  Wonder what I did wrong before.

**Pull request merged**
