### PR TITLE
Use onResponeStarted for executing userscripts

### PR DESCRIPTION
**Pull request by Sxderp**
Potential solution for #2574

### CODE REVIEW

**Comment by xor10** [comment]
@Sxderp Unfortunately, it's not working. User scripts aren't executed in the main frame, only the subframes. 
Install the use script below , go [here](https://drive.google.com/file/d/1POIcCTzIX1oPXrCiz0clf8191F-qV10_/view?usp=sharing) and check console.
```javascript
// ==UserScript==
// @name         Test Iframes
// @namespace    @GM
// @version      1.0.0
// @author       XOR
// @description  Test iframes
// @include      *
// @grant        none
// ==/UserScript==
console.log(window.location.href);
```
---------------
I made some changes and now it's working.

```diff
diff --git a/manifest.json b/manifest.json
index d096d92..cbe7491 100644
--- a/manifest.json
+++ b/manifest.json
@@ -65,6 +65,7 @@
     "storage",
     "tabs",
     "unlimitedStorage",
+    "webNavigation",
     "webRequest"
   ]
 }
diff --git a/src/bg/execute.js b/src/bg/execute.js
index a1fefb2..11babd5 100644
--- a/src/bg/execute.js
+++ b/src/bg/execute.js
@@ -5,8 +5,12 @@ content script executions.
 TODO: Make document_start execution time work as intended.
 */
 
-function executeUserscriptOnResponseStarted(detail) {
-  if (false === getGlobalEnabled()) return;
+function executeUserscriptOnResponseStartedOrOnNavigation(detail) {
+  if (false === getGlobalEnabled()
+     // or if a navigation event and a subframe...
+    || detail.transitionType === 'auto_subframe') {
+    return;
+  }
 
   var userScriptIterator = UserScriptRegistry.scriptsToRunAt(detail.url);
   for (let userScript of userScriptIterator) {
diff --git a/src/bg/execute.run.js b/src/bg/execute.run.js
index ed0e6b3..027ca8d 100644
--- a/src/bg/execute.run.js
+++ b/src/bg/execute.run.js
@@ -1,3 +1,4 @@
 chrome.webRequest.onResponseStarted.addListener(
-  executeUserscriptOnResponseStarted,
-  { 'urls': ['<all_urls>'], 'types': ['main_frame', 'sub_frame'] });
+  executeUserscriptOnResponseStartedOrOnNavigation,
+  { 'urls': ['<all_urls>'], 'types': ['sub_frame'] });
+chrome.webNavigation.onCommitted.addListener(executeUserscriptOnResponseStartedOrOnNavigation);

```

**Comment by Sxderp** [comment]
> @Sxderp Unfortunately, it's not working. User scripts aren't executed in the main frame, only the subframes.
Install the use script below , go here and check console.

Might be a bug / regression in Firefox then. Works on Firefox 52. I'll have to check it out on 57+ when I have some time. Most likely tomorrow.

**Comment by Sxderp** [comment]
Interesting. Retested on FF52 ESR, unfortunately don't have access to anything newer, and my console output is:
```
"https://drive.google.com/file/d/1POIcCTzIX1oPXrCiz0clf8191F-qV10_/view"  Test%20Iframes:281:1
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified  (unknown)
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified  (unknown)
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified  (unknown)
"https://clients6.google.com/static/proxy.html?usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.xyDspFFbPYQ.O%2Fm%3D__features__%2Fam%3DAAI%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo9vuiyYzl-xmAxJd0moShp71zG1mw#parent=https%3A%2F%2Fdrive.google.com&rpctoken=585869597"  Test%20Iframes:281:1
"https://content.googleapis.com/static/proxy.html?usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.xyDspFFbPYQ.O%2Fm%3D__features__%2Fam%3DAAI%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo9vuiyYzl-xmAxJd0moShp71zG1mw#parent=https%3A%2F%2Fdrive.google.com&rpctoken=854271513"  Test%20Iframes:281:1
"https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fdrive.google.com&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.xyDspFFbPYQ.O%2Fm%3D__features__%2Fam%3DAAI%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo9vuiyYzl-xmAxJd0moShp71zG1mw#rpctoken=390358732&forcesecure=1"  Test%20Iframes:281:1
```

I believe the first line indicates the main frame?

**Comment by Sxderp** [comment]
Just checked with 59.0a1 and it looks like my patch is still executing in all the frames. Unless I'm missing something. Could you print what you'd expect the console output to be?

**Comment by xor10** [comment]
The main frame url is missing. No error is shown.
[Demonstration](https://i.imgur.com/cVGyKVX.mp4)

**Comment by Sxderp** [comment]
Weird!
I noticed you were logged and I wasn't. So I logged in and went back to the page. Then the problem occurs.

**Comment by Sxderp** [comment]
So, tested on 52 ESR, while logged in, and mine runs on all frames. I think this may be, yet another, regression with WebExtensions with the transition into 57 era. It's kind of annoying.

**Comment by alexgit2k** [comment]
Same here with https://github.com/Sxderp/greasemonkey/tree/use-on-response-started-for-execute and the user-script [iframecheck.txt](https://github.com/greasemonkey/greasemonkey/files/1496599/iframecheck.txt)

It fires only within frames, it does not fire for the main-page and for a page without a frame it does not fire at all. Firefox 57.

**Comment by Sxderp** [comment]
I haven't touched this in a while. There's still bugs that this could potentially fix, but I feel that we should focus on #2663 . Firefox 58 was publicly released not long ago and 59 isn't far off. Furthermore, switching over to the contentScript API will be required per the recent developments in sandboxing content scripts. See #2549 .

**Pull request closed without merging**
