### PR TITLE
Monkey menu visual glitches

### LINKED ISSUE #2694: Maintain the popup scrolling position when viewing a script entry's options
Currently in GM 4.0 when clicking a script entry in the popup to view its options, and press the back '<' arrow,
then is always takes you to the top of the scripts list, regardless of your previous scrolling position.
I believe it would be more convenient if the scrolling position was maintained, 
especially when having lots of user scripts.

### PR DESCRIPTION
**Pull request by Sxderp**
Refixes #2650 
Fixes the scrolling issue of #2816 
Seems to reduce (doesn't eliminate) the ghosting effect in #2816
Inadvertently fixes #2694

### CODE REVIEW

**Comment by Sxderp** [comment]
I should also note that the duplicated `(min|max)-width` attributes are necessary. If you just set `width` you get some seriously janky effects when navigating between the script details and installed scripts.

**Comment by arantius** [comment]
> I should also note that the duplicated (min|max)-width attributes are necessary. If you just set width you get some seriously janky effects when navigating between the script details and installed scripts.

This is the sort of thing that should be called out via a comment right in line.  I noticed this myself as I tried to "fix" this, but could have easily missed its connection to the switching.

**Comment by Sxderp** [comment]
> This is the sort of thing that should be called out via a comment right in line.

Added comments

**Comment by arantius** [comment]
Looks good now, but #2822 to check cross platform.

**Pull request merged**
