### PR TITLE
GM_registerMenuCommand + @run-at document-start

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad #2139
__It is necessary to test all options!__

### CODE REVIEW

**Comment by janekptacijarabaci** [comment]
It was processed successfully... https://github.com/greasemonkey/greasemonkey/commit/ba63ca2ccaa5e1c25aee52035a3e913fcd060231

**Comment by janekptacijarabaci** [comment]
It was processed successfully... https://github.com/greasemonkey/greasemonkey/commit/ba63ca2ccaa5e1c25aee52035a3e913fcd060231

**Comment by arantius** [comment]
Whoops!  Sorry I missed this; I wasted so much time debugging it on my own.

**Comment by janekptacijarabaci** [comment]
Nothing happened :-)

**Pull request closed without merging**
