### PR TITLE
Revive i18n of @name and @description

### PR DESCRIPTION
**Pull request by esperecyan**
Resolves https://github.com/greasemonkey/greasemonkey/issues/3089

### CODE REVIEW

**Comment by arantius** [comment]
I've merged this.  I'd appreciate if anyone concerned could test build https://addons.mozilla.org/firefox/downloads/file/3711152/greasemonkey-2021.1.18.15493nightly-an+fx.xpi before we cut a release.

**Comment by Cerberus-tm** [comment]
@arantius I'd like to try it, but I get this message on the page:
"We're sorry, but we can't find what you're looking for."

**Comment by arantius** [comment]
I think they have a CDN which takes a while to become globally consistent, I'm also hosting it:

https://arantius.com/misc/gm-nightly/greasemonkey-2021.01.18.nightly.7409ca7c.xpi

**Comment by esperecyan** [comment]
@arantius Thank you for merging!
I think that it because the download link for the self-hosted add-on is only accessible by the owner.
When I tried to access the file on https:/arantius.commiscgm-nightly , I got 403 Forbidden.

**Comment by Cerberus-tm** [comment]
Yeah, I cannot access either page at the moment.

**Comment by arantius** [comment]
Sorry, been a while since I've done this.  Last link above fixed.

**Comment by Cerberus-tm** [comment]
Will download. I'm very happy you did it!

**Comment by esperecyan** [comment]
I downloaded Greasemonkey 2021.01.18.15493nightly and installed it successfully.

**Pull request merged**
