### PR TITLE
Optimizations for profiles with many tabs

### PR DESCRIPTION
**Pull request by the8472**
Makes the sandboxes more gc-friendly as mentioned in #2237 and reduces the number of observer registrations.

### CODE REVIEW

**Comment by arantius** [comment]
This pull request appears to do several distinct things, and clash with existing project style.

It would probably be a good idea to split it into two parts to discuss separately.  The one is an easy merge, the other is not.

**Comment by arantius** [comment]
Also FYI I'll be resistant to merging anything that uses language features that [JSDT](http://www.eclipse.org/webtools/jsdt/) fails to understand, as I tend to rely on functionality it provides.  When it can't parse the file, all its features break.  This basically means ES5 and above should be avoided, like the function syntax you've added.

Plus, switching an existing file to strict mode should change independently of anything else.  And I'm not sure how I feel about it yet; if we use it, we should probably be consistent about using it (i.e. everywhere).

**Comment by the8472** [comment]
Ok, I'll split it up and change the syntax.

I'll leave the 'use strict' to you. I think it's just good style since it catches scoping errors more quickly.

**Comment by arantius** [comment]
Thanks for your contribution by the way, as well as working with me to improve them.

**Comment by janekptacijarabaci** [comment]
> I'll leave the 'use strict' to you. I think it's just good style since it catches scoping errors more quickly.

e.g. after installing a script:
js-strict_error

**Comment by the8472** [comment]
btw, have you had a look at [Tern](https://github.com/angelozerr/tern.java/wiki/Tern-&-ECMAScript-support)? it seems to have es6 support

**Pull request closed without merging**
