### PR TITLE
Support GM_xmlhttpRequest referer override in e10s

### PR DESCRIPTION
**Pull request by the8472**
fixes greasemonkey/greasemonkey#2103

### CODE REVIEW

**Comment by arantius** [comment]
Is this necessary?  As I [mentioned](https://github.com/greasemonkey/greasemonkey/issues/2103#issuecomment-126738239) this works for me with no change.  (Nightly, e10s on.  Also stable, e10s not even an option yet.)

Actually, if I completely remove the non-working-in-child-processes observer stuff it continues to work.  So something has changed upstream I guess?

**Comment by the8472** [comment]
Hrrm, last time I checked it by inspecting the headers in the browser toolbox and it didn't show up in without the fix.

I'll retest again.

**Comment by the8472** [comment]
Actually, have you tested with master or with 3.5beta1, because the async messages things also contains this fix since I needed the request observer in the parent process anyway.

See 0bfa0ef82d276cf63df41585da0ff0142e04c0bc

**Comment by arantius** [comment]
Test procedure from [#2103](https://github.com/greasemonkey/greasemonkey/issues/2103#issuecomment-126738239).

Stable profile, FF41, GM3.5beta2 as built from 666ddc49318ea077277d93382712a49090d424ae .  Works.
Dev profile, FF44 e10s on, git working copy at 666ddc49318ea077277d93382712a49090d424ae .  Works.
Dev profile, FF44 e10s off, git working copy at 666ddc49318ea077277d93382712a49090d424ae .  Works.

In all cases I get the referer specified by the script, which the server is reading from request headers and echoing, logged.  If I remove the script header specification, I get NULL logged instead.

When I merged the broadcast branch, I specifically removed all of the observer/referer setting stuff.  Note that branch [has no modules/refererSetter.js](https://github.com/arantius/greasemonkey/tree/broadcast-script-config/modules) and [xmlhttprequester.js](https://github.com/arantius/greasemonkey/blob/broadcast-script-config/modules/xmlhttprequester.js) has no special referer handling.

**Pull request closed without merging**
