### PR TITLE
Add an optional simple editor which uses a plain textarea.

### PR DESCRIPTION
**Pull request by jcsteh**
This is needed by screen reader users, as CodeMirror is unfortunately not accessible. Having a separate editor is not ideal, nor is the missing functionality for screen reader users. Nevertheless, this is far better than a completely inaccessible editor. This at least allows screen reader users to read the content and do basic editing.

A more ideal alternative would be switching to [Monaco](https://microsoft.github.io/monaco-editor/), which is accessible. This would avoid the need for a separate editor and provide advanced functionality for all users. I'm not sure if that is feasible, though.

### CODE REVIEW

**Comment by jcsteh** [comment]
I discovered that this broke when creating a new script, as the ?simple query string wasn't passed in that case. Fixing that was going to introduce more ugliness, so I refactored so that the options are fetched in edit-user-script. That should also make it easier to add additional editor configurability in future.

**Comment by arantius** [comment]
Monaco looks interesting and [this example](https://github.com/microsoft/monaco-editor-samples/blob/master/browser-script-editor/index.html) makes me think that if we include its files the right way, we can load it from a web extension.

**Comment by MarcoZehe** [comment]
Any way to move this forward? This PR has been sitting here largely uncommented and unreviewed for several months.

**Comment by arantius** [comment]
I just wanted to comment to say: thanks so much for your contribution, sorry that it took so long to get to addressing it.

**Pull request merged**
