### PR TITLE
Use SVG icons

### LINKED ISSUE #2739: Switch to vector icon
Tested on Firefox 57, 58
﻿
screenshot

```xml
<xul:image
  xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"
  anonid="icon"
  class="icon"
  src="https://addons.cdn.mozilla.net/user-media/addon_icons/0/748-64.png?modified=1510954212"/>
```

The biggest icon provided by GM is not big enough. It should be at least 96x96 (192x192 or larger for high dpi displays).

Firefox can auto-sacle a big image (like 400x400) for GM, so a bigger icon always helps.

UPDATE: opened an issue for Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1422026

### PR DESCRIPTION
**Pull request by iology**
Close #2739 

Hope you like it.

addon-list

addon-profile

Toolbar:

toolbar-dark-enabled

toolbar-light-enabled

Disabled:

toolbar-dark-disabled

toolbar-light-disabled

<details><summary>Old Screenshots</summary>

greasemonkey_screenshot_addon_list

greasemonkey_screenshot_addon_profile

Toolbar:

greasemonkey_screenshot_toolbar_dark
greasemonkey_screenshot_toolbar_light

Inactive:

greasemonkey_screenshot_inactive_dark
greasemonkey_screenshot_inactive_light

</details>

### CODE REVIEW

**Comment by iology** [comment]
Just added the license: CC BY-NC-SA 4.0: https://creativecommons.org/licenses/by-nc-sa/4.0/

I don't know the license of the original image. So if you demand, CC0 public license is also fine.

**Comment by arantius** [comment]
In a message from 2007, which I can find in GMail but not on the corresponding list archive (do they expire!?) the creator says "I'll release the logo in the same license as Greasemonkey (Open source, right? It doesn't say anywhere) to make everything easy."

**Comment by iology** [comment]
Ok, I've updated the license: both MIT and CC BY-SA 4.0. The later also permits creation of derivatives in any image format.

**Comment by Sxderp** [comment]
Keeping the browser action as the original .png file?

**Comment by iology** [comment]
Don't know why it can overrides the png for browser_icon... Updated.

**Comment by arantius** [comment]
So I'm seeing the browser action button go from:

screenshot from 2018-01-05 10 51 51

to:

screenshot from 2018-01-05 10 52 10

And in the add-on manager, from:

screenshot from 2018-01-05 10 55 14

to:

screenshot from 2018-01-05 10 54 57

In AOM that's a pretty close match but something about the colors are off.  In the button, the eyes are ... glassy?  And maybe it's the lighter color, but the mouth also mostly disappears/loses detail.

**Comment by iology** [comment]
original → svg 1x svg 2x

Just polish the icon a bit. Preview: https://htmlpreview.github.io/?https://github.com/jakwings/greasemonkey/blob/7cff481e9c0cf78ad098305ce1366e79230e33af/skin/icon.svg

**Comment by iology** [comment]
original svg 1x
svg 2x

With larger eyes and bigger mouth: https://htmlpreview.github.io/?https://github.com/jakwings/greasemonkey/blob/30e549afce81872a6c905b1780677a52772f0f22/skin/icon.svg

**Comment by iology** [comment]
original svg 1x
svg 2x

The face contour and mouth match the original better now: https://htmlpreview.github.io/?https://github.com/jakwings/greasemonkey/blob/777aa6d2213f893b29df2f03ef2b5994737559a2/skin/icon.svg

**Comment by Sxderp** [comment]
Assuming the `.svg` is to be used everywhere, then the [setIcon](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/setIcon) in `src/bg/is-enabled.js` will need an update, for the `.svg` and the sizes per the 'imageData' on the above linked page.

**Comment by iology** [comment]
Among the functions from `src/bg/is-enabled.js`, it seems that only `getGlobalEnabled()` is used outside of tests. Is a grayscale icon still needed?

**Comment by Sxderp** [comment]
> Among the functions from `src/bg/is-enabled.js`, it seems that only `getGlobalEnabled()` is used outside of tests.

The other functions are used indirectly. When a 'EnabledToggle' message is sent to the background the `onEnableToggle()` function will be called. Eventually leading to `setIcon()`. In which the icon (for the browser action / Monkey Menu) is swapped depending on the current state. If the extension is disabled then the icon is set to a more muted color scheme. As far as I can tell, with your current branch, when you use the Monkey Menu to toggle the extension on / off, the icons are replaced with the original `.png` images per [these lines](https://github.com/jakwings/greasemonkey/blob/69c9a9ef075f40c2a80168410dce34576aa81a9d/src/bg/is-enabled.js#L45-L47). I linked to the MDN page describing the API in an earlier comment.

**Comment by iology** [comment]
Ah, I forgot to check the disable button on the addon page. But testing with Firefox Developer Edition, both the grayscaled icon on the addon page and the transparent one on the toolbar are auto-generated for me. The logic for using svg icons is weird here… `setIcon()` was indeed called after the menu item "Greasemonkey is active" was clicked.

disabled

**Comment by iology** [comment]
Exactly, the grayscale icon is drawn by applying the CSS rule `filter: grayscale(1)`.

**Comment by iology** [comment]
`setIcon()` doesn't work for png either. Is this bug related? https://bugzilla.mozilla.org/show_bug.cgi?id=1331746

Latest icon (the hair looks better now): https://htmlpreview.github.io/?https://github.com/jakwings/greasemonkey/blob/6fb6257201deae0bd2c1f051217dc46929e77000/skin/icon.svg

**Comment by Sxderp** [comment]
Set icon is working properly. When you toggle the add-on using the Greasemonkey menu (pressing the browser action icon on the toolbar) the icon changes.

**Comment by iology** [comment]
Ah, embarrassing… so my initial screenshots for the toolbar icon are false (no sure it is good or bad). I need to polish the svg icon more. (Currently, left:original right:svg toolbar )

**Comment by iology** [comment]
`setIcon()` updated. Latest screenshots with [the svg icon](https://htmlpreview.github.io/?https://github.com/jakwings/greasemonkey/blob/b9d72114dac02ac49754f53c1cbd7a495440f9b5/skin/icon.svg):

addon-list

addon-profile

Toolbar:

toolbar-dark-enabled

toolbar-light-enabled

Disabled:

toolbar-dark-disabled

toolbar-light-disabled

**Pull request merged**
