### PR TITLE
Fix ReferenceError with iconDownload

### LINKED ISSUE #2885: Unable to save script
There is an error in console:
ReferenceError: iconDownload is not defined[Learn More]
downloader.js:161:7

Greasemonkey 4.3beta7

### PR DESCRIPTION
**Pull request by Eselce**
Fixes #2885

### CODE REVIEW

**Comment by arantius** [comment]
Thanks.  For future reference, putting "fixes/refs #nnn" in the _commit message_ (not just a comment on the web UI) means things get automatically handled when merged, which is helpful for me.

**Comment by Eselce** [comment]
> Thanks. For future reference, putting "fixes/refs #nnn" in the commit message (not just a comment on the web UI) means things get automatically handled when merged, which is helpful for me.

@arantius I've tried to, but obviously, it failed. The commit comment was:
```
Fixed ReferenceError with iconDownload

Fixes #2885
```
`Egit` tells me to omit line 2, that should be okay. Is it `fixes #2885` with a lower `f`?

**Comment by Eselce** [comment]
Wait! Did it fail? In the notification mail, I read
`Closed #2885 via #2887.`
Was that manually?

**Comment by arantius** [comment]
Oh, does GitHub also parse PR descriptions?  TIL.

> EGit tells me to omit line 2

Why?  Seems like that tool is confused.

**Comment by arantius** [comment]
Also: Sometimes, especially for complicated PRs, I merge by hand and not by the GitHub web UI, which might be the case where it doesn't consider the PR description?

**Comment by Eselce** [comment]
`EGit` tells me:

`/!\ Second line should be empty to separate commit message header from body`

I should ignore that and use lowercase `refs`/`fixes` in future PRs. No problem!

**Comment by arantius** [comment]
Oh, that's just it telling you to put a blank line in there, which is good practice; the first entry in this numbered list: https://chris.beams.io/posts/git-commit/

**Pull request merged**
