### PR TITLE
Suggestion: The dialog resizing (for Windows OS), the template is not wrapped, style clean up

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad #2191
The suggestion (for example).

### CODE REVIEW

**Comment by arantius** [comment]
I don't understand.  These grippies are not in the kind of place that makes sense, I can't understand what they're each for.

**Comment by janekptacijarabaci** [comment]
Unfortunately, also I do not understand. What are those arrows? Arrows point to the <resizer> element - this allows you to stretch the window (in this case, horizontally).

**Comment by arantius** [comment]
Sorry I still don't understand this.  The window can be resized just like any other, by its corner.  Long text is truncated.  Why this change?

**Comment by janekptacijarabaci** [comment]
> The window can be resized just like any other, by its corner.

Confirmed on:
Ubuntu 15.04

Not confirmed on:
Windows 7/8.1 :-)
(windows are modal windows - the window resizing doesn't work)

And then I suggested: "The template is not wrapped". What is your opinion on this?

**Comment by arantius** [comment]
I don't know what "the template is not wrapped" means.

**Comment by janekptacijarabaci** [comment]
https://github.com/greasemonkey/greasemonkey/pull/2194/files#diff-bb4d6a2d4a58244882529c2436edfe21R53

I'm sorry for the big "commit". I can do better (resizing the window, new script template, fix typo...). It was just the suggestion (for simplicity).

Now:

vs.
The suggestion:

**Comment by arantius** [comment]
Oh of course that's what you mean by "the template", your earlier screenshots were just overly cropped.  Great.

Also, yes.  Windows won't let you resize this window, but there's no reason to want that behavior.

**Comment by arantius** [comment]
49b1cc8 is only two lines and gets quite close to this, what do you think?

As far as I can tell the only thing it doesn't do is allow resizing when clicking the "options" button in the AOM.

**Comment by janekptacijarabaci** [comment]
It's not occurred to me :-)

> As far as I can tell the only thing it doesn't do is allow resizing when clicking the "options" button in the AOM.

That's what this trick does:
https://bugzilla.mozilla.org/show_bug.cgi?id=267950#c9

```
javascript:opener.openDialog("chrome://greasemonkey/content/options.xul","","modal,resizable");window.close();
```

**Comment by arantius** [comment]
Calling this done, filed #2300 to track the bit that isn't.

**Comment by jerone** [comment]
Maybe force not wrapping lines in the "New User Script" dialog "Includes" and "Excludes" settings. Makes the "One per line" comment clearer.

**Comment by janekptacijarabaci** [comment]
https://github.com/greasemonkey/greasemonkey/pull/2194#issuecomment-148831736: +1

**Pull request closed without merging**
