### PR TITLE
Limit the time for AOM's "check for updates"

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
Ad #2029
The suggestion (for example).
__It is necessary to test all options!__

### CODE REVIEW

**Comment by arantius** [comment]
What is your rationale for making this configurable?  Is there not a reasonable default value that should always work?

**Comment by janekptacijarabaci** [comment]
I made it complex. You can trim it :-)

**Comment by janekptacijarabaci** [comment]
https://github.com/greasemonkey/greasemonkey/commit/ebfd75bcb6a1234186986181448a2e3a387c0e62#commitcomment-11339885

**Comment by janekptacijarabaci** [comment]
https://github.com/greasemonkey/greasemonkey/commit/ebfd75bcb6a1234186986181448a2e3a387c0e62
https://github.com/greasemonkey/greasemonkey/commit/3c14bd61f7c891a840478307f3f52a6725621db5

**Comment by janekptacijarabaci** [comment]
https://github.com/greasemonkey/greasemonkey/commit/ebfd75bcb6a1234186986181448a2e3a387c0e62
https://github.com/greasemonkey/greasemonkey/commit/3c14bd61f7c891a840478307f3f52a6725621db5

**Pull request closed without merging**
